# Generated by Django 4.1.4 on 2023-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('credit', models.IntegerField(default=0)),
                ('rooyesh', models.IntegerField(default=3)),
                ('biography', models.CharField(blank=True, default='', max_length=1003)),
                ('picture', models.ImageField(blank=True, upload_to='user/profile/')),
                ('phone_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
