# Generated by Django 4.2 on 2023-05-28 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=250)),
                ('picture', models.ImageField(blank=True, upload_to='book/')),
                ('translator', models.CharField(blank=True, max_length=50)),
                ('shabak', models.CharField(blank=True, max_length=50)),
                ('publish_year', models.CharField(blank=True, max_length=20)),
                ('is_donated', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=60)),
                ('ranking', models.IntegerField(default=0)),
                ('number_of_request', models.IntegerField(default=0)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('donator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='donator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('is_reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_book', to='Book.book')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
